### ISSUE TITLE
Handle ECONNRESET

### ISSUE THREAD

**Issue by DavidBruant** [dtc-innovation/garagiste#8]
ECONNRESET can happen. Garagiste should be resilient against ECONNRESET

**Comment by thom4parisot** [comment]
I faced a lot of them and it seems the module ended the download way too early.

```
Error Site dtc _contenus Fr tmp/PUBLICATIONS [Brouillons]/CONTENUS FR SITE  Error: Client network socket disconnected before secure TLS connection was established
    at TLSSocket.onConnectEnd (_tls_wrap.js:1324:19)
    at Object.onceWrapper (events.js:284:20)
    at TLSSocket.emit (events.js:201:15)
    at endReadableNT (_stream_readable.js:1130:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:9) {
  code: 'ECONNRESET',
  path: null,
  host: 'www.googleapis.com',
  port: 443,
  localAddress: undefined
}
```
